<?php
define('DAY_IN_HOURS', 24);
define('DAY_IN_MINUTES', DAY_IN_HOURS * 60);
define('DAY_IN_SECONDS', DAY_IN_MINUTES * 60);
define('HOUR_IN_MINUTES', 60);
define('HOUR_IN_SECONDS', HOUR_IN_MINUTES * 60);
define('MINUTE_IN_SECONDS', 60);
define('SECOND_IN_MILLISECONDS', 1000);
define('SECOND_IN_MICROSECONDS', SECOND_IN_MILLISECONDS * 1000);
define('SECOND_IN_NANOSECONDS', SECOND_IN_MICROSECONDS * 1000);